# Generated by Django 2.2.12 on 2026-06-03 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulationAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('subckt', '.subckt subcircuit definition'), ('lib', '.lib library file'), ('model', '.model device directive')], max_length=10)),
                ('raw_content', models.TextField(help_text='Original uploaded content — never executed directly')),
                ('sanitized_content', models.TextField(help_text='Whitelist-sanitized content — injected into netlists')),
                ('is_approved', models.BooleanField(default=False, help_text='Gates public gallery publishing; personal use is always allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('pin_count', models.IntegerField(blank=True, null=True)),
                ('subckt_name', models.CharField(blank=True, default='', help_text='Extracted .subckt name for netlist Xref matching', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spice_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
